version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
      - backend_data:/app/data
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./data/rss_subscriber.db
      - RSSHUB_BASE_URL=http://rssia-hub:1200
      - LOG_LEVEL=DEBUG
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - rss_network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rss_network

  # Redis缓存服务
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - rss_network

  # 自建RSShub实例（解决限流问题）
  rsshub:
    image: diygod/rsshub:chromium-bundled
    container_name: rssia-hub
    ports:
      - "1200:1200"
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://redis:6379/"
      CACHE_EXPIRE: 3600
      # 启用更多路由支持
      ALLOW_LOCALHOST: "true"
      DISALLOW_ROBOT: "false"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - rss_network
    volumes:
      - rsshub_data:/app/data

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - rss_network
    profiles:
      - production

volumes:
  backend_logs:
    driver: local
  backend_data:
    driver: local
  redis_data:
    driver: local
  rsshub_data:
    driver: local

networks:
  rss_network:
    driver: bridge 